In [6]:
%load_ext autoreload
%autoreload 2
import sys
import torch

sys.path.insert(0,'/home/aw1223/ip/agile')

from sdk.ample import Ample

from torch_geometric.datasets import FakeDataset #TODO remove
from sdk.models.models import MLP_Model,Interaction_Net_Model


dataset = FakeDataset(
                        num_graphs=1, 
                        num_nodes = 50,
                        avg_degree=1,
                        num_channels=32,
                        edge_dim=32
                    )[0]


class ToyModel(torch.nn.Module):
    def __init__(self, in_channels=32, out_channels=32, layer_count=1, hidden_dimension=32, precision = torch.float32):
        super().__init__()
        self.precision = precision
        self.layers = torch.nn.ModuleList()


        self.linear1 = MLP_Model(in_channels, out_channels) 
        self.linear1.name  = 'linear_embedder1'
        self.layers.append(self.linear1) #Used to map weights in SDK


        self.linear2 = MLP_Model(in_channels, out_channels) 
        self.linear2.name  = 'linear_embedder2'
        self.layers.append(self.linear2) #Used to map weights in SDK

        # self.int_net = Interaction_Net_Model(in_channels, out_channels, layer_count, hidden_dimension, precision)
        # self.int_net.name  = 'int_net'
        # self.layers.append(self.int_net) #Used to map weights in SDK


        for layer in self.layers:
            layer.to(self.precision)

    def forward(self, x):
        x = x.to(self.precision) 
        print(x) 
        _,x = self.linear1(x)
        print(x)
        _,x = self.linear2(x)

        # _,x = self.int_net(x, edge_index, edge_attr)
  
        return x


model = ToyModel(32,32)

dataset = FakeDataset(
                        num_graphs=1, 
                        num_nodes = 50,
                        avg_degree=1,
                        num_channels=32,
                        edge_dim=32
                    )[0]
# dataset.x = torch.tensor(dataset.x)
# External inputs {'int_net_input_1': None, 'int_net_input_2': None, 'linear_input_0': None}
#Need inputs to be sorted
print('num_nodes')
num_nodes  = len(dataset.x)
print(num_nodes)
print('num_edges')
print(dataset.num_edges)
num_edges = dataset.num_edges
inputs = [dataset.x]
out = model(*inputs)



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
num_nodes
1237
num_edges
2470
tensor([[ 9.5624,  7.8693,  7.5559,  ...,  7.8463,  8.2261,  8.5848],
        [ 0.7244,  1.2774,  2.4342,  ...,  1.5808,  1.3451,  3.2543],
        [ 2.5429, -0.0523, -1.0245,  ..., -1.9897,  1.4396,  0.3269],
        ...,
        [ 1.8471,  0.3202,  4.2415,  ...,  1.5781,  0.7262,  2.6178],
        [ 1.9142,  1.7165,  1.7725,  ...,  0.6112,  1.2124,  1.3574],
        [ 1.9348,  2.1255, -0.1326,  ...,  0.8037,  0.0488,  0.9018]])
tensor([[ 6.0679, -4.6488, -0.3091,  ...,  1.1212, -3.8670, -2.5362],
        [ 0.8679, -1.0796, -1.7851,  ..., -0.1673, -0.6762, -0.6690],
        [ 0.2360,  0.6116, -0.6975,  ..., -0.4259, -0.1509,  0.3873],
        ...,
        [ 1.3046, -1.3164,  0.0891,  ...,  1.1162, -0.7607, -0.7634],
        [ 1.3988, -0.9031,  0.0543,  ...,  1.2799, -0.7603, -1.4648],
        [ 0.6745, -1.1193, -0.6635,  ...,  0.5031,  0.0602,  0.5675]],
       grad_fn

In [7]:

%load_ext autoreload
%autoreload 2

ample = Ample()
ample.sim = True

# model = GraphLam_Model(<parameters>)
model.to_device('ample',data=inputs) #Change 

# out = model(*inputs)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Moving model to Ample
Compiling model
model name ToyModel
tensor([[ 9.5624,  7.8693,  7.5559,  ...,  7.8463,  8.2261,  8.5848],
        [ 0.7244,  1.2774,  2.4342,  ...,  1.5808,  1.3451,  3.2543],
        [ 2.5429, -0.0523, -1.0245,  ..., -1.9897,  1.4396,  0.3269],
        ...,
        [ 1.8471,  0.3202,  4.2415,  ...,  1.5781,  0.7262,  2.6178],
        [ 1.9142,  1.7165,  1.7725,  ...,  0.6112,  1.2124,  1.3574],
        [ 1.9348,  2.1255, -0.1326,  ...,  0.8037,  0.0488,  0.9018]])
tensor([[ 6.0679, -4.6488, -0.3091,  ...,  1.1212, -3.8670, -2.5362],
        [ 0.8679, -1.0796, -1.7851,  ..., -0.1673, -0.6762, -0.6690],
        [ 0.2360,  0.6116, -0.6975,  ..., -0.4259, -0.1509,  0.3873],
        ...,
        [ 1.3046, -1.3164,  0.0891,  ...,  1.1162, -0.7607, -0.7634],
        [ 1.3988, -0.9031,  0.0543,  ...,  1.2799, -0.7603, -1.4648],
        [ 0.6745, -1.1193, -0.6635,  ...,  0.5031,  0.060

1244it [00:00, 120493.13it/s]
1244it [00:00, 117267.82it/s]

Updated configuration successfully written back to file.
Overloading


In [8]:
out = model(*inputs)

tensor([[ 9.5624,  7.8693,  7.5559,  ...,  7.8463,  8.2261,  8.5848],
        [ 0.7244,  1.2774,  2.4342,  ...,  1.5808,  1.3451,  3.2543],
        [ 2.5429, -0.0523, -1.0245,  ..., -1.9897,  1.4396,  0.3269],
        ...,
        [ 1.8471,  0.3202,  4.2415,  ...,  1.5781,  0.7262,  2.6178],
        [ 1.9142,  1.7165,  1.7725,  ...,  0.6112,  1.2124,  1.3574],
        [ 1.9348,  2.1255, -0.1326,  ...,  0.8037,  0.0488,  0.9018]])
tensor([[ 6.0679, -4.6488, -0.3091,  ...,  1.1212, -3.8670, -2.5362],
        [ 0.8679, -1.0796, -1.7851,  ..., -0.1673, -0.6762, -0.6690],
        [ 0.2360,  0.6116, -0.6975,  ..., -0.4259, -0.1509,  0.3873],
        ...,
        [ 1.3046, -1.3164,  0.0891,  ...,  1.1162, -0.7607, -0.7634],
        [ 1.3988, -0.9031,  0.0543,  ...,  1.2799, -0.7603, -1.4648],
        [ 0.6745, -1.1193, -0.6635,  ...,  0.5031,  0.0602,  0.5675]],
       grad_fn=<AddmmBackward0>)
