In [20]:
%reload_ext autoreload
%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(0,'/home/aw1223/ip/agile/imports/neural-lam')
sys.path.insert(0,'/home/aw1223/ip/agile/imports/neural-lam/neural_lam')

sys.path.insert(0,'/home/aw1223/ip/agile')


import torch


from neural_lam.models.graph_lam import GraphLAM
from neural_lam.weather_dataset import WeatherDataset
from neural_lam.utils import make_mlp
from neural_lam.interaction_net import InteractionNet

from sdk.ample import Ample


import argparse
# Manually create the args Namespace object with the desired parameters
args = argparse.Namespace(
    dataset='meps_example',
    model='graph_lam',
    subset_ds=True,
    seed=42,
    n_workers=1,
    epochs=1,
    batch_size=1,
    load=None,
    restore_opt=0,
    precision=32,
    graph='1level',
    hidden_dim=64,
    hidden_layers=1,
    processor_layers=1,
    mesh_aggr='sum',
    output_std=0,
    ar_steps=1,
    loss='wmse',
    step_length=1,
    lr=0.001,
    val_interval=1,
    split='val',
    n_example_pred=1
)
print('Neural LAM Args', args)
#Change to neural-lam directory
%cd /home/aw1223/ip/worktree_a/imports/neural-lam

eval_loader = torch.utils.data.DataLoader(
                WeatherDataset(
                    args.dataset,
                    pred_length=1,
                    split=args.split,
                    subsample_step=1,
                    subset=bool(args.subset_ds),
                ),
                args.batch_size,
                shuffle=False,
                num_workers=args.n_workers,
            )


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Neural LAM Args Namespace(dataset='meps_example', model='graph_lam', subset_ds=True, seed=42, n_workers=1, epochs=1, batch_size=1, load=None, restore_opt=0, precision=32, graph='1level', hidden_dim=64, hidden_layers=1, processor_layers=1, mesh_aggr='sum', output_std=0, ar_steps=1, loss='wmse', step_length=1, lr=0.001, val_interval=1, split='val', n_example_pred=1)
/home/aw1223/ip/worktree_a/imports/neural-lam


In [22]:
ample = Ample()
model = GraphLAM(args)

Loaded graph with 70345 nodes (63784 grid, 6561 mesh)
Edges in subgraphs: m2m=51520, g2m=100656, m2g=255136


In [23]:
model.to_device('ample',data_loader=eval_loader)

Moving model to Ample
Compiling model
----------------------------------------
data Data(x=[6561, 2], num_nodes=6561)
----------------------------------------
data Data(x=[255136, 3], num_nodes=255136)
----------------------------------------
data Data(x=[100656, 3], num_nodes=100656)
----------------------------------------
data Data(x=[63784, 54], num_nodes=63784)
External inputs
name grid_embedder
['grid_embedder_input_0']
['grid_embedder_output_0']
[8, 9]
[tensor([[-0.7817, -0.9840],
        [-0.7598, -0.9840],
        [-0.7380, -0.9840],
        ...,
        [ 0.9247,  0.9877],
        [ 0.9466,  0.9877],
        [ 0.9685,  0.9877]]), tensor([[ 0.5000,  0.3319,  0.3739],
        [ 0.3884,  0.1050,  0.3739],
        [ 0.3933, -0.1218,  0.3739],
        ...,
        [ 0.3933,  0.1218, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 0.5000, -0.3319, -0.3739]]), tensor([[ 0.5000, -0.3319, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 0.3933,  0.1218, -0.3739],
    

7974it [00:00, 61481.16it/s]


name g2m_embedder
['g2m_embedder_input_0']
['g2m_embedder_output_0']
[18, 19]
[tensor([[-0.7817, -0.9840],
        [-0.7598, -0.9840],
        [-0.7380, -0.9840],
        ...,
        [ 0.9247,  0.9877],
        [ 0.9466,  0.9877],
        [ 0.9685,  0.9877]]), tensor([[ 0.5000,  0.3319,  0.3739],
        [ 0.3884,  0.1050,  0.3739],
        [ 0.3933, -0.1218,  0.3739],
        ...,
        [ 0.3933,  0.1218, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 0.5000, -0.3319, -0.3739]]), tensor([[ 0.5000, -0.3319, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 0.3933,  0.1218, -0.3739],
        ...,
        [ 0.3933, -0.1218,  0.3739],
        [ 0.3884,  0.1050,  0.3739],
        [ 0.5000,  0.3319,  0.3739]])]
dataset Data(x=[100656, 3], num_nodes=100656)
shape1 3
sub_model MLP_Model(
  (layers): ModuleList(
    (0): Linear(in_features=3, out_features=32, bias=True)
  )
)
Embeddings: []
tensor([[ 0.5000, -0.3319, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 

12583it [00:00, 62373.97it/s]


name m2g_embedder
['m2g_embedder_input_0']
['m2g_embedder_output_0']
[28, 29]
[tensor([[-0.7817, -0.9840],
        [-0.7598, -0.9840],
        [-0.7380, -0.9840],
        ...,
        [ 0.9247,  0.9877],
        [ 0.9466,  0.9877],
        [ 0.9685,  0.9877]]), tensor([[ 0.5000,  0.3319,  0.3739],
        [ 0.3884,  0.1050,  0.3739],
        [ 0.3933, -0.1218,  0.3739],
        ...,
        [ 0.3933,  0.1218, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 0.5000, -0.3319, -0.3739]])]
dataset Data(x=[255136, 3], num_nodes=255136)
shape1 3
sub_model MLP_Model(
  (layers): ModuleList(
    (0): Linear(in_features=3, out_features=32, bias=True)
  )
)
Embeddings: []
tensor([[ 0.5000,  0.3319,  0.3739],
        [ 0.3884,  0.1050,  0.3739],
        [ 0.3933, -0.1218,  0.3739],
        ...,
        [ 0.3933,  0.1218, -0.3739],
        [ 0.3884, -0.1050, -0.3739],
        [ 0.5000, -0.3319, -0.3739]])
Mapping in messages


31893it [00:00, 61598.09it/s]


name mesh_embedder
['mesh_embedder_input_0']
['mesh_embedder_output_0']
[38, 39]
[tensor([[-0.7817, -0.9840],
        [-0.7598, -0.9840],
        [-0.7380, -0.9840],
        ...,
        [ 0.9247,  0.9877],
        [ 0.9466,  0.9877],
        [ 0.9685,  0.9877]])]
dataset Data(x=[6561, 2], num_nodes=6561)
shape1 2
sub_model MLP_Model(
  (layers): ModuleList(
    (0): Linear(in_features=2, out_features=32, bias=True)
  )
)
Embeddings: []
tensor([[-0.7817, -0.9840],
        [-0.7598, -0.9840],
        [-0.7380, -0.9840],
        ...,
        [ 0.9247,  0.9877],
        [ 0.9466,  0.9877],
        [ 0.9685,  0.9877]])
Mapping in messages


821it [00:00, 66027.33it/s]


Module type not supported
ExpandToBatch
Module type not supported
ExpandToBatch
Module type not supported
InteractionNet
name encoding_grid_mlp
['grid_embedder_output_0']
['encoding_grid_mlp_output_0']
[56, 57]
[]
fake data
dataset Data(y=[24], edge_index=[2, 44], x=[24, 32], edge_weight=[44])
shape1 32
sub_model MLP_Model(
  (layers): ModuleList(
    (0): Linear(in_features=32, out_features=32, bias=True)
  )
)
Embeddings: []
tensor([[ 4.2017e+00,  5.0848e+00,  3.4851e+00,  6.5103e+00,  4.6087e+00,
          4.8609e+00,  4.1358e+00,  5.2283e+00,  3.8235e+00,  5.4148e+00,
          4.9452e+00,  5.2532e+00,  5.9751e+00,  4.7564e+00,  4.8381e+00,
          4.7669e+00,  5.2165e+00,  3.9927e+00,  5.6561e+00,  6.5191e+00,
          4.1791e+00,  4.8497e+00,  4.9555e+00,  3.3191e+00,  6.3770e+00,
          5.4788e+00,  3.5306e+00,  3.7426e+00,  5.6339e+00,  3.4703e+00,
          3.1433e+00,  4.4128e+00],
        [-6.8937e-01, -5.3295e-03,  1.5082e+00,  4.3038e-01, -9.1807e-01,
         -1.070

3it [00:00, 25317.73it/s]

name m2m_embedder
['m2m_embedder_input_0']
['m2m_embedder_output_0']
[66, 67]
[]


IndexError: pop from empty list